Update ci-databricks.yml

diff --git a/.github/workflows/ci-databricks.yml b/.github/workflows/ci-databricks.yml
--- a/.github/workflows/ci-databricks.yml
+++ b/.github/workflows/ci-databricks.yml
@@ -51,11 +51,16 @@ jobs:
           echo "Checking and listing all folders in $tests_folder_path"
           if [ -d "$tests_folder_path" ]; then
             echo "Directory exists. Listing all subdirectories that start with 'given_':"
-            find $tests_folder_path -type d -name "given_*" -print
+            find $tests_folder_path -type d -name "given_*" > given_dirs.txt
+            while IFS= read -r dir; do
+              if [ ! -f "$dir/Coverage.py" ]; then
+                echo "Missing Coverage.py in $dir"
+                exit 1
+              fi
+            done < given_dirs.txt
           else
             echo "Directory '$tests_folder_path' does not exist."
           fi
-
 
   databricks_ci_build:
     uses: Energinet-DataHub/.github/.github/workflows/databricks-build-prerelease.yml@v14
