Add ci check migration files deleted

diff --git a/.github/workflows/ci-databricks.yml b/.github/workflows/ci-databricks.yml
--- a/.github/workflows/ci-databricks.yml
+++ b/.github/workflows/ci-databricks.yml
@@ -59,7 +59,7 @@ jobs:
           SCRIPT_FILES_IN_MAIN=$(find ./source/databricks/calculation_engine/package/datamigration/migration_scripts -type f -name '*.sql' -printf "%f,")
           echo "::set-output name=script_files_in_main::$SCRIPT_FILES_IN_MAIN"
 
-      - name: Verify migration script names
+      - name: Verify migration scripts
         run: |
           CURRENT_DATETIME=$(TZ=Europe/Paris date +"%Y-%m-%d %H:%M:%S")
           #Internal Field Seperator
@@ -74,6 +74,15 @@ jobs:
           SCRIPT_FILES_IN_MAIN="${{ steps.get_script_files_in_main.outputs.script_files_in_main }}"
           # Turns comma seperated string in to an array using the IFS
           read -ra SCRIPT_FILES_IN_MAIN_ARRAY <<<"$SCRIPT_FILES_IN_MAIN"
+          
+          for item in "${SCRIPT_FILES_IN_MAIN_ARRAY[@]}"
+          do
+            # If a item from the SCRIPT_FILES_IN_MAIN_ARRAY does not exist in the SCRIPT_FILES_IN_PR_ARRAY then
+            if [[ ! " ${SCRIPT_FILES_IN_PR_ARRAY[@]} " =~ "${item}" ]]; then
+              echo "Error: Existing file: ${item} has been deleted in migration_scripts folder"
+              exit 1
+            fi
+          done
 
           # Reverse sort the SCRIPT_FILES_IN_MAIN_ARRAY to get the file with the latest prefix datetime first
           script_files_in_main_reverse_sorted=($(echo "${SCRIPT_FILES_IN_MAIN_ARRAY[@]}" | tr ' ' '\n' | sort -r))
