Update ci-databricks.yml

diff --git a/.github/workflows/ci-databricks.yml b/.github/workflows/ci-databricks.yml
--- a/.github/workflows/ci-databricks.yml
+++ b/.github/workflows/ci-databricks.yml
@@ -113,6 +113,27 @@ jobs:
             fi
           done
 
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0  # this is required to get the full history
+
+      - name: Check for changes in migration scripts
+        run: |
+          # Get a list of files changed in the last commit
+          CHANGED_FILES=$(git diff --name-only HEAD~1..HEAD)
+          # Loop through the list of changed files
+          for FILE in $CHANGED_FILES
+          do
+            # If the file is in the migration scripts directory
+            if [[ $FILE == ./source/databricks/calculation_engine/package/datamigration/migration_scripts/* ]]
+            then
+              # Fail the job
+              echo "Migration script $FILE was altered or deleted"
+              exit 1
+            fi
+          done
+
   # Tests that do not require the integration test environment
   unit_tests:
     strategy:
