build: Add migration_script_verification (#858)

diff --git a/.github/workflows/ci-databricks.yml b/.github/workflows/ci-databricks.yml
--- a/.github/workflows/ci-databricks.yml
+++ b/.github/workflows/ci-databricks.yml
@@ -25,6 +25,79 @@ jobs:
       ARCHITECTURE: 'x64'
       WHEEL_WORKING_DIRECTORY: './source/databricks'
 
+  migration_scripts_verification:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout current branch
+        uses: actions/checkout@v3
+
+      - name: Get files from PR branch
+        id: get_script_files_in_pr
+        run: |
+          # Gets all files in migration_scripts folder on the branch being merged excluding the __init__ file and put them into at comma seperated string
+          SCRIPT_FILES_IN_PR=$(find ./source/databricks/package/datamigration/migration_scripts -type f -not -name '__init__*' -printf "%f,")
+          echo "::set-output name=script_files_in_pr::$SCRIPT_FILES_IN_PR"
+
+      - name: Checkout main branch
+        uses: actions/checkout@v3
+        with:
+          ref: main
+
+      - name: Get files from main branch
+        id: get_script_files_in_main
+        run: |
+          # Gets all files in migration_scripts folder on the main branch excluding the __init__ file and put them into at comma seperated string
+          SCRIPT_FILES_IN_MAIN=$(find ./source/databricks/package/datamigration/migration_scripts -type f -not -name '__init__*' -printf "%f,")
+          echo "::set-output name=script_files_in_main::$SCRIPT_FILES_IN_MAIN"
+
+      - name: Verify migration script names
+        run: |
+          CURRENT_DATETIME=$(TZ=Europe/Paris date +"%Y-%m-%d %H:%M:%S")
+          #Internal Field Seperator
+          IFS=','
+
+          # Get the comma seperated string saved to output script_files_in_pr
+          SCRIPT_FILES_IN_PR="${{ steps.get_script_files_in_pr.outputs.script_files_in_pr }}"
+          # Turns comma seperated string in to an array using the IFS
+          read -ra SCRIPT_FILES_IN_PR_ARRAY <<<"$SCRIPT_FILES_IN_PR"
+
+          # Get the comma separated string saved to output script_files_in_main
+          SCRIPT_FILES_IN_MAIN="${{ steps.get_script_files_in_main.outputs.script_files_in_main }}"
+          # Turns comma seperated string in to an array using the IFS
+          read -ra SCRIPT_FILES_IN_MAIN_ARRAY <<<"$SCRIPT_FILES_IN_MAIN"
+
+          # Reverse sort the SCRIPT_FILES_IN_MAIN_ARRAY to get the file with the latest prefix datetime first
+          script_files_in_main_reverse_sorted=($(echo "${SCRIPT_FILES_IN_MAIN_ARRAY[@]}" | tr ' ' '\n' | sort -r))
+          # Turn script_files_in_main_reverse_sorted into a array (the array will only have one item, since it wont look past a new line)
+          read -ra LATEST_SCRIPT_FILE_IN_MAIN <<<"$script_files_in_main_reverse_sorted"
+
+          # Create a datetime from the prefix of the first item in the LATEST_SCRIPT_FILE_IN_MAIN array
+          LATEST_SCRIPT_FILE_IN_MAIN_DATETIME=$(date -d "${LATEST_SCRIPT_FILE_IN_MAIN[0]:0:8} ${LATEST_SCRIPT_FILE_IN_MAIN[0]:8:2}:${LATEST_SCRIPT_FILE_IN_MAIN[0]:10:2}" +"%Y-%m-%d %H:%M:%S")
+          
+          for item in "${SCRIPT_FILES_IN_PR_ARRAY[@]}"
+          do
+            # If a item from the SCRIPT_FILES_IN_PR_ARRAY does not exist in the SCRIPT_FILES_IN_MAIN_ARRAY then
+            if [[ ! " ${SCRIPT_FILES_IN_MAIN_ARRAY[@]} " =~ "${item}" ]]; then
+              # Create a datetime from the prefix of the item that was not in the SCRIPT_FILES_IN_MAIN_ARRAY
+              UNIQUE_SCRIPT_FILE_IN_PR_DATETIME=$(date -d "${item:0:8} ${item:8:2}:${item:10:2}" +"%Y-%m-%d %H:%M:%S")
+              # Fail if the items datetime is less than the LATEST_SCRIPT_FILE_IN_MAIN_DATETIME
+              if [[ $UNIQUE_SCRIPT_FILE_IN_PR_DATETIME < $LATEST_SCRIPT_FILE_IN_MAIN_DATETIME ]]; then
+                echo "New migration script file: ${item} can not be before the latest migration script"
+                exit 1
+              fi
+              # Fail if the items datetime is equal the LATEST_SCRIPT_FILE_IN_MAIN_DATETIME
+              if [[ $UNIQUE_SCRIPT_FILE_IN_PR_DATETIME == $LATEST_SCRIPT_FILE_IN_MAIN_DATETIME ]]; then
+                echo "New migration script file: ${item} can not be the same time as the latest migration script"
+                exit 1
+              fi
+              # Fail if the items datetime is greater than the CURRENT_DATETIME
+              if [[ $UNIQUE_SCRIPT_FILE_IN_PR_DATETIME > $CURRENT_DATETIME ]]; then
+                echo "New migration script file: ${item} can not be later than current datetime"
+                exit 1
+              fi
+            fi
+          done
+
   databricks_ci_test:
     uses: Energinet-DataHub/.github/.github/workflows/python-ci.yml@v10
     with:
