Update ci-databricks.yml

diff --git a/.github/workflows/ci-databricks.yml b/.github/workflows/ci-databricks.yml
--- a/.github/workflows/ci-databricks.yml
+++ b/.github/workflows/ci-databricks.yml
@@ -34,6 +34,11 @@ jobs:
       - name: Get files from current branch
         id: get_current_files
         run: |
+          CURRENT_FILES=$(find ./source/databricks/package/datamigration/migration_scripts -type f | grep -v '^./source/databricks/package/datamigration/migration_scripts/__init__.py$' | grep -v '^[0-9]\{12\}.*$')
+          if [ -n "$CURRENT_FILES" ]; then
+            echo "Error: the following files in the migration_scripts directory do not have the expected timestamp prefix: $CURRENT_FILES"
+            exit 1
+          fi
           CURRENT_FILES=$(find ./source/databricks/package/datamigration/migration_scripts -type f -not -name '__*' -printf "%f\n" | sort -r)
           echo "::set-output name=current_files::$CURRENT_FILES"
 
@@ -52,7 +57,7 @@ jobs:
         run: |
           CURRENT_FILES="${{ steps.get_current_files.outputs.current_files }}"
           MAIN_FILES="${{ steps.get_main_files.outputs.main_files }}"
-          echo ${$CURRENT_FILES:0:14}
+          echo $CURRENT_FILES
           echo $MAIN_FILES
 
 
